-- Phase 17: Question Quality Pipeline
-- Adds: QuestionQualityIssue, QuestionVersion, MarketingContent, QualityHealthReport
-- Upgrades: QuestionReport with structured triage / SLA fields
-- Idempotent (safe to re-run)

-- ============================================================================
-- 1. Upgrade QuestionReport: add structured fields, change default status
-- ============================================================================

ALTER TABLE "QuestionReport"
  ADD COLUMN IF NOT EXISTS "reasonCategory" TEXT,
  ADD COLUMN IF NOT EXISTS "targetOption"   TEXT,
  ADD COLUMN IF NOT EXISTS "triageVerdict"  TEXT,
  ADD COLUMN IF NOT EXISTS "triageNotes"    TEXT,
  ADD COLUMN IF NOT EXISTS "triagedByModel" TEXT,
  ADD COLUMN IF NOT EXISTS "triagedAt"      TIMESTAMP,
  ADD COLUMN IF NOT EXISTS "assignedTo"     TEXT,
  ADD COLUMN IF NOT EXISTS "resolvedAt"     TIMESTAMP,
  ADD COLUMN IF NOT EXISTS "resolvedBy"     TEXT,
  ADD COLUMN IF NOT EXISTS "resolution"     TEXT;

-- Migrate legacy status values to new uppercase enum-style strings
UPDATE "QuestionReport" SET "status" = 'PENDING'  WHERE "status" = 'pending';
UPDATE "QuestionReport" SET "status" = 'IN_REVIEW' WHERE "status" = 'reviewed';
UPDATE "QuestionReport" SET "status" = 'RESOLVED_FIXED' WHERE "status" = 'resolved';

-- New default for future inserts
ALTER TABLE "QuestionReport" ALTER COLUMN "status" SET DEFAULT 'PENDING';

CREATE INDEX IF NOT EXISTS "QuestionReport_questionId_status_idx"
  ON "QuestionReport"("questionId","status");

-- ============================================================================
-- 2. QuestionQualityIssue: rule-based + agent-detected issues
-- ============================================================================

CREATE TABLE IF NOT EXISTS "QuestionQualityIssue" (
  "id"          TEXT NOT NULL DEFAULT gen_random_uuid()::text,
  "questionId"  TEXT NOT NULL,
  "ruleId"      TEXT NOT NULL,
  "severity"    TEXT NOT NULL DEFAULT 'MEDIUM',
  "detail"      TEXT NOT NULL,
  "meta"        JSONB,
  "status"      TEXT NOT NULL DEFAULT 'OPEN',
  "contentHash" TEXT,
  "detectedAt"  TIMESTAMP NOT NULL DEFAULT NOW(),
  "resolvedAt"  TIMESTAMP,
  "resolvedBy"  TEXT,
  "resolution"  TEXT,
  PRIMARY KEY ("id"),
  CONSTRAINT "QuestionQualityIssue_questionId_fkey"
    FOREIGN KEY ("questionId") REFERENCES "Question"("id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "QuestionQualityIssue_questionId_idx"
  ON "QuestionQualityIssue"("questionId");
CREATE INDEX IF NOT EXISTS "QuestionQualityIssue_status_severity_idx"
  ON "QuestionQualityIssue"("status","severity");
CREATE INDEX IF NOT EXISTS "QuestionQualityIssue_ruleId_status_idx"
  ON "QuestionQualityIssue"("ruleId","status");
CREATE UNIQUE INDEX IF NOT EXISTS "QuestionQualityIssue_questionId_ruleId_contentHash_key"
  ON "QuestionQualityIssue"("questionId","ruleId","contentHash");

-- ============================================================================
-- 3. QuestionVersion: change history / rollback
-- ============================================================================

CREATE TABLE IF NOT EXISTS "QuestionVersion" (
  "id"             TEXT NOT NULL DEFAULT gen_random_uuid()::text,
  "questionId"     TEXT NOT NULL,
  "snapshot"       JSONB NOT NULL,
  "changedBy"      TEXT NOT NULL,
  "reason"         TEXT,
  "agentInitiated" BOOLEAN NOT NULL DEFAULT FALSE,
  "createdAt"      TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY ("id"),
  CONSTRAINT "QuestionVersion_questionId_fkey"
    FOREIGN KEY ("questionId") REFERENCES "Question"("id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "QuestionVersion_questionId_createdAt_idx"
  ON "QuestionVersion"("questionId","createdAt" DESC);

-- ============================================================================
-- 4. MarketingContent: content generated by marketing-team agents
-- ============================================================================

CREATE TABLE IF NOT EXISTS "MarketingContent" (
  "id"           TEXT NOT NULL DEFAULT gen_random_uuid()::text,
  "contentType"  TEXT NOT NULL,
  "platform"     TEXT,
  "title"        TEXT,
  "body"         TEXT NOT NULL,
  "meta"         JSONB,
  "status"       TEXT NOT NULL DEFAULT 'draft',
  "modelUsed"    TEXT,
  "generatedAt"  TIMESTAMP NOT NULL DEFAULT NOW(),
  "approvedAt"   TIMESTAMP,
  "publishedAt"  TIMESTAMP,
  "publishedUrl" TEXT,
  "metrics"      JSONB,
  PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "MarketingContent_contentType_status_idx"
  ON "MarketingContent"("contentType","status");
CREATE INDEX IF NOT EXISTS "MarketingContent_generatedAt_idx"
  ON "MarketingContent"("generatedAt" DESC);

-- ============================================================================
-- 5. QualityHealthReport: daily/weekly snapshots
-- ============================================================================

CREATE TABLE IF NOT EXISTS "QualityHealthReport" (
  "id"             TEXT NOT NULL DEFAULT gen_random_uuid()::text,
  "periodType"     TEXT NOT NULL,
  "period"         TEXT NOT NULL,
  "totalQuestions" INTEGER NOT NULL,
  "approvedCount"  INTEGER NOT NULL,
  "draftCount"     INTEGER NOT NULL,
  "archivedCount"  INTEGER NOT NULL,
  "openIssueCount" INTEGER NOT NULL,
  "healthScore"    INTEGER NOT NULL,
  "summary"        JSONB NOT NULL,
  "narrative"      TEXT,
  "modelUsed"      TEXT,
  "createdAt"      TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "QualityHealthReport_periodType_createdAt_idx"
  ON "QualityHealthReport"("periodType","createdAt" DESC);
CREATE UNIQUE INDEX IF NOT EXISTS "QualityHealthReport_periodType_period_key"
  ON "QualityHealthReport"("periodType","period");
