#!/usr/bin/env node
/**
 * NCLEX-RN vocabulary seeder.
 *
 * Scans ALL *.json files under scripts/vocab-seed/ (generated by
 * parallel Claude agents), validates them, merges and deduplicates
 * by word, and upserts into VocabularyWord. Safe to re-run.
 *
 * Usage:
 *   node scripts/seed-vocab.js                 # seed everything
 *   node scripts/seed-vocab.js --truncate      # wipe VocabularyWord first
 *   node scripts/seed-vocab.js --dry-run       # validate + count only
 *   node scripts/seed-vocab.js --force         # seed even if validation errors
 */

const { Pool } = require("pg");
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

try { require("dotenv").config(); } catch { /* dotenv optional */ }

const BATCH_DIR = path.join(__dirname, "vocab-seed");
// Dynamically scan all JSON files in the folder
const BATCH_FILES = fs.existsSync(BATCH_DIR)
  ? fs.readdirSync(BATCH_DIR).filter((f) => f.endsWith(".json")).sort()
  : [];

const VALID_CATEGORIES = new Set([
  "Pharmacology",
  "Assessment",
  "Pathophysiology",
  "Lab Values & Diagnostics",
  "Procedures & Skills",
  "Medical-Surgical",
  "Maternal-Newborn",
  "Pediatric",
  "Mental Health",
  "Patient Safety & Priority",
  "NCLEX Test-Taking Language",
  "Nursing Process & Delegation",
]);
const VALID_POS = new Set(["noun", "verb", "adjective", "abbr"]);
const VALID_DIFFICULTY = new Set(["EASY", "MEDIUM", "HARD"]);

function parseArgs(argv) {
  const flags = {};
  for (const a of argv.slice(2)) {
    if (a.startsWith("--")) {
      const [k, v] = a.replace(/^--/, "").split("=");
      flags[k] = v ?? true;
    }
  }
  return flags;
}

function validateEntry(entry, source) {
  const errs = [];
  if (!entry || typeof entry !== "object") return [`${source}: not an object`];
  if (typeof entry.word !== "string" || !entry.word.trim()) errs.push(`${source}: missing word`);
  if (!VALID_POS.has(entry.partOfSpeech)) errs.push(`${source}[${entry.word}]: bad partOfSpeech ${entry.partOfSpeech}`);
  if (typeof entry.definitionEn !== "string" || !entry.definitionEn) errs.push(`${source}[${entry.word}]: missing definitionEn`);
  if (typeof entry.definitionZh !== "string" || !entry.definitionZh) errs.push(`${source}[${entry.word}]: missing definitionZh`);
  if (!VALID_CATEGORIES.has(entry.category)) errs.push(`${source}[${entry.word}]: bad category "${entry.category}"`);
  if (![1, 2, 3].includes(entry.tier)) errs.push(`${source}[${entry.word}]: bad tier ${entry.tier}`);
  if (!VALID_DIFFICULTY.has(entry.difficulty)) errs.push(`${source}[${entry.word}]: bad difficulty ${entry.difficulty}`);
  if (!Array.isArray(entry.synonyms)) errs.push(`${source}[${entry.word}]: synonyms must be array`);
  return errs;
}

async function main() {
  const flags = parseArgs(process.argv);
  const dryRun = !!flags["dry-run"];
  const truncate = !!flags.truncate;

  console.log(`[seed-vocab] Loading ${BATCH_FILES.length} batch files from ${BATCH_DIR}`);
  const all = [];
  const errors = [];

  for (const file of BATCH_FILES) {
    const p = path.join(BATCH_DIR, file);
    if (!fs.existsSync(p)) {
      errors.push(`Missing batch file: ${p}`);
      continue;
    }
    let arr;
    try {
      arr = JSON.parse(fs.readFileSync(p, "utf8"));
    } catch (err) {
      errors.push(`${file}: JSON parse error — ${err.message}`);
      continue;
    }
    if (!Array.isArray(arr)) {
      errors.push(`${file}: not a JSON array`);
      continue;
    }
    console.log(`[seed-vocab] ${file}: ${arr.length} entries`);
    for (const e of arr) {
      const entryErrs = validateEntry(e, file);
      if (entryErrs.length) errors.push(...entryErrs);
      else all.push(e);
    }
  }

  // Dedupe by word (case-insensitive). Later files override earlier ones.
  const byWord = new Map();
  for (const e of all) {
    const key = e.word.trim().toLowerCase();
    if (byWord.has(key)) {
      console.warn(`[seed-vocab] Duplicate word: ${e.word} — keeping last occurrence`);
    }
    byWord.set(key, e);
  }
  const merged = Array.from(byWord.values());

  console.log(`[seed-vocab] Loaded ${merged.length} unique entries (${all.length} before dedupe)`);
  if (errors.length) {
    console.error(`[seed-vocab] Validation errors (${errors.length}):`);
    for (const e of errors.slice(0, 20)) console.error(`  - ${e}`);
    if (errors.length > 20) console.error(`  ... and ${errors.length - 20} more`);
    if (!flags.force) {
      console.error("[seed-vocab] Aborting. Pass --force to seed anyway.");
      process.exit(1);
    }
  }

  if (dryRun) {
    const byCategory = {};
    for (const e of merged) byCategory[e.category] = (byCategory[e.category] ?? 0) + 1;
    console.log("[seed-vocab] Category distribution:");
    for (const [k, v] of Object.entries(byCategory)) console.log(`  ${k.padEnd(35)} ${v}`);
    console.log("[seed-vocab] --dry-run OK, no writes performed");
    return;
  }

  const connectionString = process.env.DATABASE_URL;
  if (!connectionString) {
    console.error("[seed-vocab] DATABASE_URL is not set");
    process.exit(1);
  }

  const pool = new Pool({ connectionString, max: 4 });
  const client = await pool.connect();

  try {
    if (truncate) {
      console.log('[seed-vocab] Truncating "VocabularyWord" table...');
      await client.query('TRUNCATE TABLE "VocabularyWord" RESTART IDENTITY CASCADE');
    }

    let upserted = 0;
    for (const e of merged) {
      const id = crypto.randomUUID();
      const now = new Date();
      await client.query(
        `INSERT INTO "VocabularyWord" (
           id, word, "partOfSpeech", "definitionEn", "definitionZh", category,
           tier, difficulty, "exampleEn", "exampleZh", synonyms, "memoryHook",
           tags, status, "createdBy", "createdAt", "updatedAt"
         ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8::"Difficulty",$9,$10,$11,$12,$13,$14::"QuestionStatus",$15,$16,$17)
         ON CONFLICT (word) DO UPDATE SET
           "partOfSpeech" = EXCLUDED."partOfSpeech",
           "definitionEn" = EXCLUDED."definitionEn",
           "definitionZh" = EXCLUDED."definitionZh",
           category       = EXCLUDED.category,
           tier           = EXCLUDED.tier,
           difficulty     = EXCLUDED.difficulty,
           "exampleEn"    = EXCLUDED."exampleEn",
           "exampleZh"    = EXCLUDED."exampleZh",
           synonyms       = EXCLUDED.synonyms,
           "memoryHook"   = EXCLUDED."memoryHook",
           tags           = EXCLUDED.tags,
           status         = EXCLUDED.status,
           "updatedAt"    = EXCLUDED."updatedAt"`,
        [
          id,
          e.word.trim(),
          e.partOfSpeech,
          e.definitionEn,
          e.definitionZh,
          e.category,
          e.tier,
          e.difficulty,
          e.exampleEn ?? null,
          e.exampleZh ?? null,
          Array.isArray(e.synonyms) ? e.synonyms : [],
          e.memoryHook ?? null,
          Array.isArray(e.tags) ? e.tags : [],
          "APPROVED",
          "claude",
          now,
          now,
        ]
      );
      upserted++;
    }

    const total = await client.query('SELECT COUNT(*)::int AS n FROM "VocabularyWord"');
    console.log(`[seed-vocab] Upserted ${upserted} entries. Table now has ${total.rows[0].n} rows.`);
  } finally {
    client.release();
    await pool.end();
  }
}

main().catch((err) => {
  console.error("[seed-vocab] Fatal:", err);
  process.exit(1);
});
